version: "3.7"

services:
  backend-users:
    build:
      dockerfile: ./src/backend/users/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
    ports:
      - 8001:8001

  backend-pizzas:
    build:
      dockerfile: ./src/backend/pizzas/Dockerfile
    depends_on:
      - backend-users
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
    ports:
      - 8002:8002

  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
      - db-vol:/var/lib/postgresql/data

  frontend-web:
    build:
      dockerfile: ./src/frontend/web/Dockerfile
    depends_on:
      - backend-users
      - backend-pizzas
    env_file:
      - .env
    environment:
      BACKEND_USERS_HOST: ${BACKEND_USERS_HOST}
      BACKEND_PIZZAS_HOST: ${BACKEND_PIZZAS_HOST}
    ports:
      - 8000:8000

volumes:
  db-vol: null
