version: "3.7"

services:
  src:
    build:
      context: ../
      dockerfile: ./.devcontainer/src/Dockerfile
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_EMAIL=${GITHUB_EMAIL}
    depends_on:
      - db
    env_file:
      - .env
    environment:
      BACKEND_USERS_HOST: ${BACKEND_USERS_HOST}
      BACKEND_PIZZAS_HOST: ${BACKEND_PIZZAS_HOST}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
    volumes:
      - "..:/workspace:cached"

  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
      - db-vol:/var/lib/postgresql/data

volumes:
  db-vol: null
