from os import environ

DATABASE_HOST = environ["DATABASE_HOST"]
DATABASE_NAME = environ["DATABASE_NAME"]
DATABASE_PASSWORD = environ["DATABASE_PASSWORD"]
DATABASE_USERNAME = environ["DATABASE_USERNAME"]

JWT_SECRET_KEY = environ["JWT_SECRET_KEY"]
